apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  username: cm9vdA==  # root
  password: a292ZW5nZXJzMTIzNA==  # kovengers1234

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  application.yml: |
    spring:
      application:
        name: user-service
      autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      datasource:
        url: jdbc:mysql://172.16.211.102:3306/newcord_user_db
        username: root
        password: kovengers1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        master:
          jdbcUrl: jdbc:mysql://172.16.211.102:3306/newcord_user_db
          username: root
          password: kovengers1234
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          jdbcUrl: jdbc:mysql://172.16.211.107:3307/newcord_user_db
          username: root
          password: kovengers1234
          driver-class-name: com.mysql.cj.jdbc.Driver
        #    url: jdbc:mysql://localhost:3306/newcord_userservice_db
        #    username: kovengers
        #    password: kovengers1234
        #driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        generate-ddl: true
        properties:
          hibernate:
            format_sql: true
      thymeleaf:
        prefix: classpath:/static/
    kakao:
      api_key: a61af306bdb89fc8bbbaced44fb4fef0
      redirect_uri: http://localhost:8080/api/auth/login
    jwt:
      secret: 01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 604800

    cloud:
      kakao:
        object-storage:
          endpoint: https://objectstorage.kr-central-2.kakaoi.io
          region: kr-central-2
          bucket: user-service
          access-key: 9136c2a42a2f43889b8e0b1c54e2d082
          secret-key: 2a41342d7fee4f3696913079846d8729
          project-id : 3e614ed3c42f48858e6668a30d7b3c1a
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: kovengers/user-service:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: password
          - name: SPRING_CONFIG_LOCATION
            value: /config/application.yml
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: user-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8080    
  type: LoadBalancer
