apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  username: cm9vdA==  # root
  password: a292ZW5nZXJzMTIzNA==  # kovengers1234

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  application.yml: |
    spring:
      main:
        allow-bean-definition-overriding: true
      datasource:
        
        url: jdbc:mysql://172.16.211.102:3306/newcord_user_db
        # username: Secrets 에서 가져옴
        # password: Secrets 에서 가져옴
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: create 
        show-sql: true 
        generate-ddl: true 
        properties:
          hibernate:
            format_sql: true 
      thymeleaf:
        prefix: classpath:/static/
    kakao:
      api_key: a61af306bdb89fc8bbbaced44fb4fef0
      redirect_uri: http://localhost:8080/api/auth/login
    jwt:
      secret: 01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 604800

  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: kovengers/user-service:latest
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: password
          - name: SPRING_CONFIG_LOCATION
            value: /config/application.yml
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: user-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8080    
  type: LoadBalancer
