apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prom-server
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv_prom_server"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prom-alertmgr
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv_prom_alertmgr"
