apiVersion: v1
kind: Secret
metadata:
  name: article-service-secrets
type: Opaque
data:
  username: cm9vdA==  # root
  password: a292ZW5nZXJzMTIzNA==  # kovengers1234
  rabbitmq-username: YWRtaW4=  # admin
  rabbitmq-password: YWRtaW4=  # admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service
  labels:
    app.kubernetes.io/name: article-service
    app: article-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: article-service
        app: article-service
    spec:
      containers:
      - name: article-service
        image: kovengers/article-service:88
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: article-service-secrets
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: article-service-secrets
                key: password
          - name: SPRING_CONFIG_LOCATION
            value: /config/application.yml
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: article-service-config
      nodeSelector:
        kakaoi.io/kke-nodepool: backend-node

---
apiVersion: v1
kind: Service
metadata:
  name: article-service-service
spec:
  selector:
    app: article-service
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8080    
  type: ClusterIP
