apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kong-postgresql-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-kong-postgresql
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data"