apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
  labels:
    app.kubernetes.io/name: fastapi-service
    app: fastapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
        app: fastapi-service
    spec:
      containers:
      - name: fastapi-container
        image: kovengers/fast-api:5
        ports:
        - containerPort: 8000
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: fastapi-service-config
        - secretRef:
            name: fastapi-service-secrets
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
      nodeSelector:
        kakaoi.io/kke-nodepool: backend-node

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-service-secrets
type: Opaque
data:
  KAKAO_RESTAPI_KEY: ZmFkN2FmOGRlMTcxNjJmNjc1NWM0OGQ4ZDMwODAwNjY= # base64 인코딩
  MONGO_URL: bW9uZ29kYitzcnY6Ly9rZWFrb3ZlbmdlcnM6YTVCRFlvazV1TDBQckZOZUBjbHVzdGVyMC5tNjE5YWJjLm1vbmdvZGIubmV0Lw==
  SECRET_KEY: and0c2VjcmV0a2V5
  openai_api_key: YmI4NjQ1ZGI5NjM5NDM5ZmE5Y2NmNTRjNDg1ZTY4ZGE=
  openai_azure_endpoint: aHR0cHM6Ly9rZWEta292ZW5nZXJzLWdwdC5vcGVuYWkuYXp1cmUuY29tLw==