apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    @include pods-fluent.conf
    @include elastic-fluent.conf  # for logs storage in ElasticSearch

  pods-fluent.conf: |-
    <filter **>
      @type concat
      key log
      multiline_start_regexp /^(\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{0,3})/
    </filter>

    <source>
      @type tail
      read_from_head true
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>
    

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
    </filter>

    #Parses Spring logs 
    <filter kubernetes.**>
      @id spring_parser
      @type parser
      key_name log
      <parse>
        @type regexp
        expression /^(?<logtime>[^ ]* [^ ]*) +(?<level>[^ ]*) +(?<pid>[^ ]*) +--- +\[ *(?<thread>[^ ]*)\] +(?<class>[^ ]*) +: +(?<message>.*)$/
        time_key logtime
        time_type string
        time_format %Y-%m-%d %H:%M:%S.%L
        timezone +09:00
        multiline true
        keep_time_key true
      </parse>
      #hash_value_field parsed # add hash dept
      reserve_data true
      emit_invalid_record_to_error false
    </filter>

  elastic-fluent.conf: |-
    <match **>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.default.svc.cluster.local'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      index_name "logstash-#{Time.now.strftime('%Y.%m.%d')}"
      type_name fluentd
      include_timestamp true

      log_es_400_reason "#{ENV['FLUENT_ELASTICSEARCH_LOG_ES_400_REASON'] || 'true'}"
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'logstash'}"
      logstash_format "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT'] || 'true'}"

    </match>

