apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  username: cm9vdA==  # root
  password: a292ZW5nZXJzMTIzNA==  # kovengers1234

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app.kubernetes.io/name: user-service
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
        app: user-service
    spec:
      containers:
      - name: user-service
        image: kovengers/user-service:110
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-service-secrets
                key: password
          - name: SPRING_CONFIG_LOCATION
            value: /config/application.yml
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: user-service-config
      nodeSelector:
        kakaoi.io/kke-nodepool: backend-node

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8081
  type: ClusterIP
