apiVersion: v1
data:
  application.yml: |-
    server:
      port: 8081
      tomcat:
        max-http-post-size: 31457280
    spring:
      application:
        name: user-service
      autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      datasource:
        # url: jdbc:mysql://172.16.211.102:3306/newcord_user_db
        # username: root
        # password: kovengers1234
        # driver-class-name: com.mysql.cj.jdbc.Driver
        master:
          jdbcUrl: jdbc:mysql://43.203.255.68:3306/newcord_user_db
          username: root
          password: kovengers1234
          driver-class-name: com.mysql.cj.jdbc.Driver
          maximum-pool-size: 10
          minimum-idle: 4
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-timeout: 30000
        slave:
          jdbcUrl: jdbc:mysql://43.203.255.68:3307/slave_user_db
          username: root
          password: kovengers1234
          driver-class-name: com.mysql.cj.jdbc.Driver
          maximum-pool-size: 10
          minimum-idle: 4
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-timeout: 30000
        #    url: jdbc:mysql://localhost:3306/newcord_userservice_db
        #    username: kovengers
        #    password: kovengers1234
        #driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        generate-ddl: true
        properties:
          hibernate:
            format_sql: true
      thymeleaf:
        prefix: classpath:/static/

      servlet:
        multipart:
          max-file-size: 30MB
          max-request-size: 30MB


    kakao:
      api_key: a61af306bdb89fc8bbbaced44fb4fef0
      redirect_uri: http://localhost:3000/api/auth/login
    jwt:
      secret: 01254cd9f9f67bab5529f1d210a20d93eab0aa9d09d681e3b201b36a4069fd6b
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 604800

    cloud:
      kakao:
        object-storage:
          endpoint: https://objectstorage.kr-central-2.kakaoi.io
          region: kr-central-2
          bucket: user-service
          access-key: 9136c2a42a2f43889b8e0b1c54e2d082
          secret-key: 2a41342d7fee4f3696913079846d8729
          project-id : 3e614ed3c42f48858e6668a30d7b3c1a


    springdoc:
      api-docs:
        enabled: true
        path: '/v3/api-docs'
      swagger-ui:
        path: '/swagger-ui'
        config-url: '/users/v3/api-docs/swagger-config'
        url: '/users/v3/api-docs'
        doc-expansion: none
        disable-swagger-default-url: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: user-service-config
